In [1]:
import numpy as np 
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df=pd.read_csv('covid_19.csv')

In [4]:
df.head()

,country,continent,population,day,time,Cases,Recovered,Deaths,Tests
0,Saint-Helena,Africa,6115.0,2024-06-30,2024-06-30T16:15:16+00:00,2166,2.0,NaN,NaN
1,Falkland-Islands,South-America,3539.0,2024-06-30,2024-06-30T16:15:16+00:00,1930,1930.0,NaN,8632.0
2,Montserrat,North-America,4965.0,2024-06-30,2024-06-30T16:15:16+00:00,1403,1376.0,8.0,17762.0
3,Diamond-Princess,NaN,NaN,2024-06-30,2024-06-30T16:15:16+00:00,712,699.0,13.0,NaN
4,Vatican-City,Europe,799.0,2024-06-30,2024-06-30T16:15:16+00:00,29,29.0,NaN,NaN

In [5]:
df.isnull().sum()

country        0
continent      2
population     9
day            0
time           0
Cases          0
Recovered     48
Deaths         5
Tests         25
dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['Tests']),df['Tests'],test_size=0.2)

In [12]:
X_train

,country,continent,population,day,time,Cases,Recovered,Deaths
64,Madagascar,Africa,29178077.0,2024-06-30,2024-06-30T16:15:14+00:00,68486,66862.0,1426.0
141,Libya,Africa,7040745.0,2024-06-30,2024-06-30T16:15:12+00:00,507274,500835.0,6437.0
226,Italy,Europe,60262770.0,2024-06-30,2024-06-30T16:15:10+00:00,26723249,26361218.0,196487.0
210,Cuba,North-America,11305652.0,2024-06-30,2024-06-30T16:15:11+00:00,1115251,1106660.0,8530.0
96,Trinidad-and-Tobago,North-America,1406585.0,2024-06-30,2024-06-30T16:15:13+00:00,191496,187078.0,4390.0
...,...,...,...,...,...,...,...,...
89,French-Guiana,South-America,314169.0,2024-06-30,2024-06-30T16:15:13+00:00,98041,11254.0,420.0
162,Laos,Asia,7481023.0,2024-06-30,2024-06-30T16:15:12+00:00,218970,NaN,758.0
104,Cameroon,Africa,27911548.0,2024-06-30,2024-06-30T16:15:13+00:00,125379,123280.0,1974.0
67,Mauritania,Africa,4901981.0,2024-06-30,2024-06-30T16:15:14+00:00,63848,62471.0,997.0
191,Iraq,Asia,42164965.0,2024-06-30,2024-06-30T16:15:11+00:00,2465545,2439497.0,25375.0

In [18]:
from sklearn.compose import ColumnTransformer

In [22]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['Recovered']),
    ('tnf2',OrdinalEncoder(),['Cases']),
    ('tnf3',OneHotEncoder(sparse_output=False,drop='first'),['continent'])
],remainder='passthrough')

In [25]:
transformer.fit_transform(X_train).shape

(190, 14)

In [27]:
transformer.fit_transform(X_test).shape

(48, 12)